ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS supplier_code VARCHAR(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS gstin VARCHAR(50) DEFAULT '',
  ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS state VARCHAR(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS pincode VARCHAR(20) DEFAULT '',
  ADD COLUMN IF NOT EXISTS categories JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bank_info JSONB DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_suppliers_supplier_code ON suppliers(supplier_code);
